# Step 1: Build stage
FROM node:20 AS build
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --configuration production

# Step 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/sobhwmasafront-end /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
